// src/components/station/FavoriteAlertsPanel.vue
<script setup lang="ts">
import type { FavoriteAlert } from "@/types/station";

defineProps<{
  alerts: FavoriteAlert[];
}>();
</script>

<template>
  <div class="d-flex flex-column ga-3">
    <v-alert
      v-for="alert in alerts"
      :key="alert.id"
      :color="alert.severity"
      variant="tonal"
    >
      <div class="d-flex flex-column ga-1">
        <strong>{{ alert.title }}</strong>
        <span>{{ alert.description }}</span>
      </div>
    </v-alert>
  </div>
</template>

// src/components/station/FavoriteAlertsPanel.tsx
import type { FavoriteAlert } from "@/types/station";
import { Alert } from "@/components/ui/alert";

interface FavoriteAlertsPanelProps {
  alerts: FavoriteAlert[];
}

export const FavoriteAlertsPanel = ({ alerts }: FavoriteAlertsPanelProps) => {
  if (alerts.length === 0) {
    return null;
  }

  return (
    <div className="space-y-3">
      {alerts.map((alert) => (
        <Alert key={alert.id} variant={alert.severity}>
          <div className="space-y-1">
            <strong className="block">{alert.title}</strong>
            <span>{alert.description}</span>
          </div>
        </Alert>
      ))}
    </div>
  );
};
