// src/components/layout/AppHeader.tsx
import { Fuel, MoonStar, SunMedium } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useFuelStationsStore } from "@/store/useFuelStationsStore";

export const AppHeader = () => {
  const themeName = useFuelStationsStore((state) => state.themeName);
  const setTheme = useFuelStationsStore((state) => state.setTheme);
  const isDark = themeName === "fuelDark";

  return (
    <header className="sticky top-0 z-20 border-b border-white/20 bg-white/70 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/55">
      <div className="container flex items-center justify-between py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-teal-600 to-sky-600 text-white shadow-lg shadow-teal-700/20">
            <Fuel className="h-5 w-5" />
          </div>
          <div>
            <p className="text-[0.65rem] font-extrabold uppercase tracking-[0.24em] text-slate-500 dark:text-slate-300/70">
              FuelFlash React Edition
            </p>
            <h1 className="font-display text-lg tracking-tight">Comparateur carburants geolocalise</h1>
          </div>
        </div>

        <Button onClick={() => setTheme(isDark ? "fuelLight" : "fuelDark")} size="icon" variant="tonal">
          {isDark ? <SunMedium className="h-4 w-4" /> : <MoonStar className="h-4 w-4" />}
        </Button>
      </div>
    </header>
  );
};

// src/components/layout/AppHeader.vue
<script setup lang="ts">
import { computed } from "vue";
import { useFuelStationsStore } from "@/stores/fuelStations";

const stationStore = useFuelStationsStore();

const isDark = computed(() => stationStore.themeName === "fuelDark");

const toggleTheme = () => {
  stationStore.setTheme(isDark.value ? "fuelLight" : "fuelDark");
};
</script>

<template>
  <v-app-bar
    class="header-bar"
    flat
  >
    <v-container class="d-flex align-center justify-space-between py-3">
      <div class="d-flex align-center ga-3">
        <v-avatar
          class="header-bar__badge"
          size="46"
        >
          <v-icon
            color="white"
            icon="mdi-fuel"
            size="24"
          />
        </v-avatar>

        <div>
          <p class="header-bar__eyebrow mb-1">Comparateur carburants geolocalise</p>
          <h1 class="header-bar__title">FuelFlash</h1>
        </div>
      </div>

      <v-btn
        :icon="isDark ? 'mdi-white-balance-sunny' : 'mdi-weather-night'"
        class="header-bar__theme"
        color="secondary"
        variant="tonal"
        @click="toggleTheme"
      />
    </v-container>
  </v-app-bar>
</template>

<style scoped>
.header-bar {
  position: sticky;
  top: 0;
  z-index: 10;
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(18px);
  border-bottom: 1px solid rgba(15, 23, 42, 0.05);
}

.header-bar__badge {
  background: linear-gradient(135deg, rgb(var(--v-theme-primary)), rgb(var(--v-theme-info)));
  box-shadow: 0 12px 30px rgba(15, 118, 110, 0.25);
}

.header-bar__eyebrow {
  font-size: 0.7rem;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  color: rgba(15, 23, 42, 0.58);
}

.header-bar__title {
  margin: 0;
  font-family: var(--ff-display);
  font-size: 1.15rem;
  letter-spacing: -0.04em;
}

.header-bar__theme {
  backdrop-filter: blur(12px);
}

.v-theme--fuelDark .header-bar {
  background: rgba(13, 31, 39, 0.68);
  border-color: rgba(148, 163, 184, 0.08);
}

.v-theme--fuelDark .header-bar__eyebrow {
  color: rgba(226, 247, 241, 0.62);
}
</style>
