// src/components/common/LocationPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import type {
  Coordinates,
  GeocodingResult,
  LocationSource,
  MockLocation,
} from "@/types/station";

const props = defineProps<{
  isGeolocating: boolean;
  isSearchingLocation: boolean;
  geoError: string | null;
  geocodingError: string | null;
  locationLabel: string | null;
  locationSource: LocationSource;
  userPosition: Coordinates | null;
  manualLocationId: string | null;
  searchQuery: string;
  searchResults: GeocodingResult[];
  mockLocations: MockLocation[];
}>();

const emit = defineEmits<{
  locate: [];
  refresh: [];
  demo: [];
  selectManual: [locationId: string];
  searchAddress: [query: string];
  selectSearchResult: [result: GeocodingResult];
}>();

const localSearchQuery = ref(props.searchQuery);

watch(
  () => props.searchQuery,
  (value) => {
    localSearchQuery.value = value;
  },
);

const sourceLabel = computed(() => {
  switch (props.locationSource) {
    case "browser":
      return "Position GPS";
    case "manual":
      return "Position manuelle";
    case "demo":
      return "Mode demonstration";
    case "search":
      return "Recherche libre";
    default:
      return "Aucune position";
  }
});

const coordinatesLabel = computed(() => {
  if (!props.userPosition) {
    return null;
  }

  return `${props.userPosition.lat.toFixed(5)}, ${props.userPosition.lng.toFixed(5)}`;
});

const runSearch = () => {
  emit("searchAddress", localSearchQuery.value);
};
</script>

<template>
  <v-card class="glass-card pa-5 pa-md-6">
    <div class="d-flex flex-column flex-md-row ga-6 justify-space-between">
      <div class="location-panel__copy">
        <p class="location-panel__eyebrow mb-2">Geolocalisation</p>
        <h3 class="text-h5 section-title mb-2">Retrouvez les meilleures stations autour de vous</h3>
        <p class="location-panel__text mb-4">
          Autorisez la geolocalisation pour un resultat live, choisissez une position
          simulee ou recherchez librement une ville/adresse en France.
        </p>

        <div class="d-flex flex-wrap ga-3">
          <v-btn
            color="primary"
            :loading="isGeolocating"
            prepend-icon="mdi-crosshairs-gps"
            @click="emit('locate')"
          >
            Utiliser ma position
          </v-btn>
          <v-btn
            color="secondary"
            prepend-icon="mdi-refresh"
            variant="tonal"
            @click="emit('refresh')"
          >
            Actualiser
          </v-btn>
          <v-btn
            color="accent"
            prepend-icon="mdi-map-marker-star"
            @click="emit('demo')"
          >
            Position de demonstration
          </v-btn>
        </div>
      </div>

      <div class="location-panel__inputs">
        <v-sheet
          class="location-panel__status pa-4 mb-4"
          color="surface"
          rounded="xl"
        >
          <div class="d-flex align-center ga-3">
            <v-avatar
              color="primary"
              size="42"
              variant="tonal"
            >
              <v-icon icon="mdi-map-marker-radius" />
            </v-avatar>
            <div>
              <p class="text-body-2 mb-1">{{ sourceLabel }}</p>
              <strong>{{ locationLabel ?? "Choisissez une position pour commencer" }}</strong>
              <p
                v-if="coordinatesLabel"
                class="location-panel__coords mt-2 mb-0"
              >
                Coordonnees detectees : {{ coordinatesLabel }}
              </p>
            </div>
          </div>
        </v-sheet>

        <v-autocomplete
          :items="mockLocations"
          :model-value="manualLocationId"
          clearable
          item-title="label"
          item-value="id"
          label="Ville de demonstration"
          prepend-inner-icon="mdi-map-search-outline"
          @update:model-value="(value) => value && emit('selectManual', String(value))"
        />

        <div class="d-flex ga-2 mt-3">
          <v-text-field
            v-model="localSearchQuery"
            class="flex-grow-1"
            clearable
            density="comfortable"
            hide-details
            label="Rechercher une ville ou une adresse"
            prepend-inner-icon="mdi-home-search-outline"
            @keydown.enter.prevent="runSearch"
          />
          <v-btn
            color="primary"
            :loading="isSearchingLocation"
            prepend-icon="mdi-magnify"
            @click="runSearch"
          >
            Rechercher
          </v-btn>
        </div>

        <v-list
          v-if="searchResults.length > 0"
          class="location-panel__search-results mt-3"
          bg-color="transparent"
        >
          <v-list-item
            v-for="result in searchResults"
            :key="result.id"
            append-icon="mdi-chevron-right"
            class="location-panel__result"
            :subtitle="result.address"
            :title="`${result.label} - ${result.city}`"
            @click="emit('selectSearchResult', result)"
          />
        </v-list>

        <v-alert
          v-if="geoError"
          class="mt-4"
          color="warning"
          icon="mdi-alert-circle-outline"
          variant="tonal"
        >
          {{ geoError }}
        </v-alert>

        <v-alert
          v-if="geocodingError"
          class="mt-4"
          color="info"
          icon="mdi-map-search"
          variant="tonal"
        >
          {{ geocodingError }}
        </v-alert>
      </div>
    </div>
  </v-card>
</template>

<style scoped>
.location-panel__copy {
  flex: 1 1 60%;
}

.location-panel__inputs {
  flex: 1 1 26rem;
}

.location-panel__eyebrow {
  font-size: 0.74rem;
  text-transform: uppercase;
  letter-spacing: 0.14em;
  color: rgb(var(--v-theme-primary));
  font-weight: 800;
}

.location-panel__text {
  color: rgba(15, 23, 42, 0.68);
  line-height: 1.6;
}

.location-panel__status {
  border: 1px solid rgba(15, 23, 42, 0.06);
}

.location-panel__coords {
  font-size: 0.8rem;
  color: rgba(15, 23, 42, 0.62);
  font-family: var(--ff-display);
  letter-spacing: -0.02em;
}

.location-panel__search-results {
  border-radius: 20px;
  background: rgba(255, 255, 255, 0.72);
}

.location-panel__result {
  border-radius: 16px;
}

.location-panel__result + .location-panel__result {
  margin-top: 0.25rem;
}

.v-theme--fuelDark .location-panel__text {
  color: rgba(226, 247, 241, 0.74);
}

.v-theme--fuelDark .location-panel__status {
  border-color: rgba(148, 163, 184, 0.08);
}

.v-theme--fuelDark .location-panel__coords {
  color: rgba(226, 247, 241, 0.68);
}

.v-theme--fuelDark .location-panel__search-results {
  background: rgba(13, 31, 39, 0.72);
}
</style>

// src/components/common/LocationPanel.tsx
import { LoaderCircle, MapPin, MapPinned, Navigation, RefreshCw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Alert } from "@/components/ui/alert";
import type { Coordinates, GeocodingResult, LocationSource, MockLocation } from "@/types/station";

interface LocationPanelProps {
  isGeolocating: boolean;
  isSearchingLocation: boolean;
  geoError: string | null;
  geocodingError: string | null;
  locationLabel: string | null;
  locationSource: LocationSource;
  userPosition: Coordinates | null;
  manualLocationId: string | null;
  searchQuery: string;
  searchResults: GeocodingResult[];
  mockLocations: MockLocation[];
  onLocate: () => void;
  onRefresh: () => void;
  onDemo: () => void;
  onSelectManual: (value: string) => void;
  onSearchAddress: (query: string) => void;
  onSelectSearchResult: (result: GeocodingResult) => void;
}

const getSourceLabel = (locationSource: LocationSource) => {
  switch (locationSource) {
    case "browser":
      return "Position GPS";
    case "manual":
      return "Position manuelle";
    case "demo":
      return "Mode demonstration";
    case "search":
      return "Recherche libre";
    default:
      return "Aucune position";
  }
};

export const LocationPanel = ({
  isGeolocating,
  isSearchingLocation,
  geoError,
  geocodingError,
  locationLabel,
  locationSource,
  userPosition,
  manualLocationId,
  searchQuery,
  searchResults,
  mockLocations,
  onLocate,
  onRefresh,
  onDemo,
  onSelectManual,
  onSearchAddress,
  onSelectSearchResult,
}: LocationPanelProps) => {
  return (
    <Card className="glass-panel">
      <CardContent className="grid gap-6 p-5 md:grid-cols-[minmax(0,1fr)_26rem] md:p-6">
        <div className="space-y-5">
          <div className="space-y-3">
            <p className="text-xs font-extrabold uppercase tracking-[0.24em] text-primary">Geolocalisation</p>
            <h3 className="font-display text-2xl tracking-tight">Retrouvez les meilleures stations autour de vous</h3>
            <p className="max-w-2xl text-sm leading-7 text-muted-foreground">
              Autorisez la geolocalisation pour un resultat live, choisissez une position simulee ou recherchez
              librement une ville ou une adresse en France.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <Button onClick={onLocate}>
              {isGeolocating ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Navigation className="h-4 w-4" />}
              Utiliser ma position
            </Button>
            <Button onClick={onRefresh} variant="tonal">
              <RefreshCw className="h-4 w-4" />
              Actualiser
            </Button>
            <Button onClick={onDemo} variant="accent">
              <MapPinned className="h-4 w-4" />
              Position de demonstration
            </Button>
          </div>
        </div>

        <div className="space-y-4">
          <div className="rounded-[24px] border border-border/70 bg-card/80 p-4">
            <div className="flex items-start gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                <MapPin className="h-5 w-5" />
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">{getSourceLabel(locationSource)}</p>
                <p className="font-semibold">{locationLabel ?? "Choisissez une position pour commencer"}</p>
                {userPosition ? (
                  <p className="font-display text-xs text-muted-foreground">
                    Coordonnees detectees : {userPosition.lat.toFixed(5)}, {userPosition.lng.toFixed(5)}
                  </p>
                ) : null}
              </div>
            </div>
          </div>

          <label className="space-y-2 text-sm font-medium">
            <span>Ville de demonstration</span>
            <select
              className="h-11 w-full rounded-2xl border border-border bg-card px-4 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
              onChange={(event) => event.target.value && onSelectManual(event.target.value)}
              value={manualLocationId ?? ""}
            >
              <option value="">Choisir une ville</option>
              {mockLocations.map((location) => (
                <option key={location.id} value={location.id}>
                  {location.label}
                </option>
              ))}
            </select>
          </label>

          <div className="flex gap-2">
            <Input
              defaultValue={searchQuery}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  onSearchAddress((event.target as HTMLInputElement).value);
                }
              }}
              placeholder="Rechercher une ville ou une adresse"
            />
            <Button
              onClick={(event) => {
                const input = (event.currentTarget.parentElement?.querySelector("input") as HTMLInputElement | null)?.value ?? "";
                onSearchAddress(input);
              }}
            >
              {isSearchingLocation ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
              Rechercher
            </Button>
          </div>

          {searchResults.length > 0 ? (
            <div className="rounded-[24px] border border-border/70 bg-card/70 p-2">
              {searchResults.map((result) => (
                <button
                  className="flex w-full flex-col rounded-2xl px-3 py-3 text-left transition hover:bg-muted"
                  key={result.id}
                  onClick={() => onSelectSearchResult(result)}
                  type="button"
                >
                  <span className="text-sm font-semibold">{`${result.label} • ${result.city}`}</span>
                  <span className="text-xs text-muted-foreground">{result.address}</span>
                </button>
              ))}
            </div>
          ) : null}

          {geoError ? <Alert variant="warning">{geoError}</Alert> : null}
          {geocodingError ? <Alert variant="info">{geocodingError}</Alert> : null}
        </div>
      </CardContent>
    </Card>
  );
};
