// src/components/filters/FilterBar.tsx
import { cn } from "@/lib/utils";
import { sortModeCopy } from "@/utils/format";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import type { FuelType, ServiceType, SortMode } from "@/types/station";

interface FilterBarProps {
  selectedFuel: FuelType;
  radiusKm: number;
  openOnly: boolean;
  selectedServices: ServiceType[];
  sortMode: SortMode;
  fuelOptions: readonly FuelType[];
  serviceOptions: readonly ServiceType[];
  onSelectedFuelChange: (value: FuelType) => void;
  onRadiusKmChange: (value: number) => void;
  onOpenOnlyChange: (value: boolean) => void;
  onSelectedServicesChange: (value: ServiceType[]) => void;
  onSortModeChange: (value: SortMode) => void;
}

export const FilterBar = ({
  selectedFuel,
  radiusKm,
  openOnly,
  selectedServices,
  sortMode,
  fuelOptions,
  serviceOptions,
  onSelectedFuelChange,
  onRadiusKmChange,
  onOpenOnlyChange,
  onSelectedServicesChange,
  onSortModeChange,
}: FilterBarProps) => {
  return (
    <Card>
      <CardContent className="space-y-5 p-5">
        <div className="space-y-3">
          <p className="text-xs font-extrabold uppercase tracking-[0.24em] text-primary">Filtres</p>
          <div className="flex flex-wrap gap-2">
            {fuelOptions.map((fuel) => (
              <button
                className={cn(
                  "rounded-full border px-4 py-2 text-sm font-semibold transition",
                  selectedFuel === fuel
                    ? "border-primary bg-primary text-primary-foreground shadow-lg shadow-primary/25"
                    : "border-border bg-card hover:bg-muted",
                )}
                key={fuel}
                onClick={() => onSelectedFuelChange(fuel)}
                type="button"
              >
                {fuel}
              </button>
            ))}
          </div>
        </div>

        <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_220px_auto] lg:items-center">
          <div className="space-y-3">
            <div className="flex items-center justify-between text-sm">
              <span>Rayon de recherche</span>
              <strong>{radiusKm} km</strong>
            </div>
            <Slider max={25} min={2} onValueChange={([value]) => onRadiusKmChange(value)} step={1} value={[radiusKm]} />
          </div>

          <Select
            onValueChange={onSortModeChange}
            options={Object.entries(sortModeCopy).map(([value, label]) => ({
              value: value as SortMode,
              label,
            }))}
            value={sortMode}
          />

          <label className="flex items-center gap-3 rounded-full border border-border bg-card px-4 py-3 text-sm font-medium">
            <Switch checked={openOnly} onCheckedChange={onOpenOnlyChange} />
            Stations ouvertes uniquement
          </label>
        </div>

        <div className="space-y-3">
          <p className="text-sm font-medium">Services souhaites</p>
          <div className="flex flex-wrap gap-2">
            {serviceOptions.map((service) => {
              const active = selectedServices.includes(service);
              return (
                <button
                  className="rounded-full"
                  key={service}
                  onClick={() =>
                    onSelectedServicesChange(
                      active ? selectedServices.filter((item) => item !== service) : [...selectedServices, service],
                    )
                  }
                  type="button"
                >
                  <Badge variant={active ? "accent" : "outline"}>{service}</Badge>
                </button>
              );
            })}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

// src/components/filters/FilterBar.vue
<script setup lang="ts">
import { computed } from "vue";
import { sortModeCopy } from "@/utils/format";
import type { FuelType, ServiceType, SortMode } from "@/types/station";

const props = defineProps<{
  selectedFuel: FuelType;
  radiusKm: number;
  openOnly: boolean;
  selectedServices: ServiceType[];
  sortMode: SortMode;
  fuelOptions: readonly FuelType[];
  serviceOptions: readonly ServiceType[];
}>();

const emit = defineEmits<{
  "update:selectedFuel": [fuel: FuelType];
  "update:radiusKm": [value: number];
  "update:openOnly": [value: boolean];
  "update:selectedServices": [value: ServiceType[]];
  "update:sortMode": [value: SortMode];
}>();

const sortItems = computed(() =>
  (Object.keys(sortModeCopy) as SortMode[]).map((value) => ({
    title: sortModeCopy[value],
    value,
  })),
);
</script>

<template>
  <v-card class="surface-card pa-4 pa-md-5">
    <div class="d-flex flex-column ga-5">
      <div>
        <p class="text-overline mb-2">Filtres</p>
        <v-chip-group
          :model-value="selectedFuel"
          column
          mandatory
          @update:model-value="(value) => emit('update:selectedFuel', value)"
        >
          <v-chip
            v-for="fuel in fuelOptions"
            :key="fuel"
            :value="fuel"
            color="primary"
            filter
            size="large"
            variant="elevated"
          >
            {{ fuel }}
          </v-chip>
        </v-chip-group>
      </div>

      <div class="d-flex flex-column flex-lg-row ga-4 align-start align-lg-center">
        <div class="flex-grow-1 w-100">
          <div class="d-flex justify-space-between align-center mb-2">
            <span class="text-body-2">Rayon de recherche</span>
            <strong>{{ radiusKm }} km</strong>
          </div>
          <v-slider
            :max="25"
            :min="2"
            :model-value="radiusKm"
            :step="1"
            color="primary"
            hide-details
            thumb-label
            @update:model-value="(value) => emit('update:radiusKm', Number(value))"
          />
        </div>

        <v-select
          class="filter-bar__select"
          :items="sortItems"
          :model-value="sortMode"
          hide-details
          item-title="title"
          item-value="value"
          label="Trier par"
          prepend-inner-icon="mdi-sort"
          @update:model-value="(value) => emit('update:sortMode', value as SortMode)"
        />

        <v-switch
          :model-value="openOnly"
          class="filter-bar__switch"
          color="primary"
          hide-details
          inset
          label="Stations ouvertes uniquement"
          @update:model-value="(value) => emit('update:openOnly', Boolean(value))"
        />
      </div>

      <v-select
        :items="serviceOptions"
        :model-value="selectedServices"
        chips
        clearable
        closable-chips
        label="Services souhaités"
        multiple
        prepend-inner-icon="mdi-tune-variant"
        @update:model-value="(value) => emit('update:selectedServices', value as ServiceType[])"
      />
    </div>
  </v-card>
</template>

<style scoped>
.filter-bar__switch {
  min-width: 260px;
}

.filter-bar__select {
  min-width: 200px;
}
</style>
