// src/components/map/StationsMap.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { storeToRefs } from "pinia";
import { useRouter } from "vue-router";
import L from "leaflet";
import "leaflet.markercluster";
import { useFuelStationsStore } from "@/stores/fuelStations";
import { formatDistance, formatDriveTime, formatPrice } from "@/utils/format";
import { getGoogleMapsDirectionsUrl } from "@/utils/navigation";
import type { Coordinates, FuelType, StationWithMetrics } from "@/types/station";

const props = defineProps<{
  userPosition: Coordinates | null;
  stations: StationWithMetrics[];
  selectedFuel: FuelType;
  radiusKm: number;
  bestStationId?: string | null;
}>();

const router = useRouter();
const stationStore = useFuelStationsStore();
const { themeName } = storeToRefs(stationStore);

const mapElement = ref<HTMLDivElement | null>(null);
const mapShell = ref<HTMLDivElement | null>(null);
const isFullscreen = ref(false);
const selectedStationId = ref<string | null>(null);

let map: L.Map | null = null;
let overlayLayer: L.LayerGroup | null = null;
let stationClusterLayer: L.MarkerClusterGroup | null = null;
let baseTileLayer: L.TileLayer | null = null;
let currentBounds: L.LatLngBounds | null = null;

const tileLayerConfig = computed(() => {
  if (themeName.value === "fuelDark") {
    return {
      url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
      options: {
        subdomains: "abcd",
        maxZoom: 20,
        attribution: "&copy; OpenStreetMap contributors &copy; CARTO",
      },
    };
  }

  return {
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    options: {
      subdomains: "abcd",
      maxZoom: 20,
      attribution: "&copy; OpenStreetMap contributors &copy; CARTO",
    },
  };
});

const hasBestStation = computed(() => props.stations.some((station) => station.id === props.bestStationId));
const pricedStations = computed(() => props.stations.filter((station) => station.selectedFuelPrice != null));
const mobilePriceMarkerIds = computed(() => pricedStations.value.slice(0, 2).map((station) => station.id));
const selectedStation = computed(
  () => props.stations.find((station) => station.id === selectedStationId.value) ?? null,
);

const createMarkerIcon = (
  className: string,
  options?: {
    label?: string;
    state?: "open" | "closed";
  },
) =>
  L.divIcon({
    className: "",
    html: `
      <div class="map-marker-shell">
        <div class="map-marker-status map-marker-status--${options?.state ?? "open"}"></div>
        <div class="${className}"></div>
        ${options?.label ? `<div class="map-marker-price">${options.label}</div>` : ""}
      </div>
    `,
    iconSize: [84, 54],
    iconAnchor: [16, 16],
  });

const formatBrandMeta = (station: StationWithMetrics) => {
  if (station.brandSource === "osm") {
    return `Enseigne enrichie via OpenStreetMap : ${station.brand}`;
  }

  if (station.brandSource === "inferred") {
    return `Enseigne estimee : ${station.brand}`;
  }

  if (station.brandSource === "not_provided") {
    return "Enseigne non communiquee - source officielle";
  }

  return station.brand;
};

const summarizeServices = (station: StationWithMetrics) => station.services.slice(0, 3).join(" - ");

const popupContent = (station: StationWithMetrics) => {
  const stationUrl = `/station/${station.id}`;
  const directionsUrl = getGoogleMapsDirectionsUrl(station.lat, station.lng);
  const statusClass = station.isOpen ? "" : " map-popup__status--closed";
  const servicesSummary = summarizeServices(station);

  return `
    <div class="map-popup">
      <h4 class="map-popup__title">${station.name}</h4>
      <p class="map-popup__meta">${formatBrandMeta(station)} - ${station.address}, ${station.city}</p>
      <div class="map-popup__price-row">
        <span class="map-popup__fuel">${props.selectedFuel}</span>
        <strong class="map-popup__price">${formatPrice(station.selectedFuelPrice)}</strong>
      </div>
      <p class="map-popup__meta">${formatDistance(station.distanceKm)} - ~ ${formatDriveTime(station.estimatedDriveMinutes)}</p>
      <p class="map-popup__meta">${station.openingHours}</p>
      <span class="map-popup__status${statusClass}">
        ${station.isOpen ? "Ouverte" : "Fermee"}
      </span>
      ${
        servicesSummary
          ? `<div class="map-popup__services">
              <span class="map-popup__service">${servicesSummary}</span>
            </div>`
          : ""
      }
      <div class="map-popup__actions">
        <a class="map-popup__button map-popup__button--ghost" href="${stationUrl}">Voir details</a>
        <a class="map-popup__button" href="${directionsUrl}" target="_blank" rel="noopener noreferrer">Y aller</a>
      </div>
    </div>
  `;
};

const applyBaseLayer = () => {
  if (!map) {
    return;
  }

  if (baseTileLayer) {
    map.removeLayer(baseTileLayer);
  }

  baseTileLayer = L.tileLayer(tileLayerConfig.value.url, tileLayerConfig.value.options).addTo(map);
};

const ensureMap = () => {
  if (!mapElement.value || map) {
    return;
  }

  map = L.map(mapElement.value, {
    zoomControl: false,
  }).setView([48.8566, 2.3522], 12);

  applyBaseLayer();
  L.control.zoom({ position: "bottomright" }).addTo(map);
  overlayLayer = L.layerGroup().addTo(map);
  stationClusterLayer = L.markerClusterGroup({
    showCoverageOnHover: false,
    spiderfyOnMaxZoom: true,
    maxClusterRadius: 56,
    iconCreateFunction: (cluster) =>
      L.divIcon({
        className: "map-cluster",
        html: `<span>${cluster.getChildCount()}</span>`,
        iconSize: [42, 42],
      }),
  }).addTo(map);
};

const fitMapToContent = (bounds: L.LatLngTuple[]) => {
  if (!map) {
    return;
  }

  if (bounds.length > 1) {
    currentBounds = L.latLngBounds(bounds);
    map.fitBounds(currentBounds, {
      padding: [40, 40],
      maxZoom: 14,
    });
    return;
  }

  currentBounds = null;

  if (props.userPosition) {
    map.setView([props.userPosition.lat, props.userPosition.lng], 13);
  }
};

const recenterMap = () => {
  if (!map) {
    return;
  }

  if (currentBounds) {
    map.fitBounds(currentBounds, {
      padding: [40, 40],
      maxZoom: 14,
    });
    return;
  }

  if (props.userPosition) {
    map.setView([props.userPosition.lat, props.userPosition.lng], 13);
  }
};

const invalidateMapSize = () => {
  window.setTimeout(() => {
    map?.invalidateSize();
    recenterMap();
  }, 180);
};

const renderMap = () => {
  if (!map || !overlayLayer || !stationClusterLayer) {
    return;
  }

  overlayLayer.clearLayers();
  stationClusterLayer.clearLayers();

  const bounds: L.LatLngTuple[] = [];

  if (props.userPosition) {
    const userLatLng: L.LatLngTuple = [props.userPosition.lat, props.userPosition.lng];
    const searchBounds = L.latLng(userLatLng).toBounds(props.radiusKm * 1000);

    bounds.push(userLatLng);
    bounds.push([searchBounds.getNorthEast().lat, searchBounds.getNorthEast().lng]);
    bounds.push([searchBounds.getSouthWest().lat, searchBounds.getSouthWest().lng]);

    L.circle(userLatLng, {
      radius: props.radiusKm * 1000,
      color: "#0f766e",
      fillColor: "#5eead4",
      fillOpacity: 0.07,
      opacity: 0.9,
      weight: 1.2,
      dashArray: "8 8",
    }).addTo(overlayLayer);

    L.circle(userLatLng, {
      radius: 260,
      color: "#0f766e",
      fillColor: "#5eead4",
      fillOpacity: 0.16,
      weight: 1.2,
    }).addTo(overlayLayer);

    L.marker(userLatLng, {
      icon: createMarkerIcon("map-user-pin"),
    })
      .bindPopup(props.userPosition.label ?? "Votre position")
      .addTo(overlayLayer);
  }

  props.stations.forEach((station) => {
    const latLng: L.LatLngTuple = [station.lat, station.lng];
    const isBest = station.id === props.bestStationId;
    const showPriceLabel = isBest || mobilePriceMarkerIds.value.includes(station.id);
    const marker = L.marker(latLng, {
      icon: createMarkerIcon(isBest ? "map-station-pin map-station-pin--best" : "map-station-pin", {
        label: showPriceLabel && station.selectedFuelPrice != null ? formatPrice(station.selectedFuelPrice) : undefined,
        state: station.isOpen ? "open" : "closed",
      }),
    });

    marker.bindPopup(popupContent(station));
    marker.on("click", () => {
      selectedStationId.value = station.id;
    });

    stationClusterLayer?.addLayer(marker);
    bounds.push(latLng);
  });

  fitMapToContent(bounds);
};

const syncFullscreenState = () => {
  isFullscreen.value = document.fullscreenElement === mapShell.value;
  invalidateMapSize();
};

const toggleFullscreen = async () => {
  if (!mapShell.value) {
    return;
  }

  if (document.fullscreenElement === mapShell.value) {
    await document.exitFullscreen();
    return;
  }

  await mapShell.value.requestFullscreen();
};

const openSelectedStation = () => {
  if (selectedStation.value) {
    router.push({ name: "station-detail", params: { id: selectedStation.value.id } });
  }
};

watch(
  () => props.bestStationId,
  (value) => {
    if (value && !selectedStationId.value) {
      selectedStationId.value = value;
    }
  },
  { immediate: true },
);

watch(
  () => props.stations.map((station) => station.id),
  (ids) => {
    if (selectedStationId.value && !ids.includes(selectedStationId.value)) {
      selectedStationId.value = props.bestStationId ?? ids[0] ?? null;
    }
  },
  { immediate: true },
);

onMounted(() => {
  ensureMap();
  renderMap();
  document.addEventListener("fullscreenchange", syncFullscreenState);
});

watch(
  () => [props.userPosition, props.stations, props.selectedFuel, props.radiusKm, props.bestStationId],
  () => {
    renderMap();
  },
  { deep: true },
);

watch(tileLayerConfig, () => {
  applyBaseLayer();
  invalidateMapSize();
});

onBeforeUnmount(() => {
  document.removeEventListener("fullscreenchange", syncFullscreenState);
  map?.remove();
  map = null;
  baseTileLayer = null;
  currentBounds = null;
});
</script>

<template>
  <v-card class="surface-card overflow-hidden">
    <div class="d-flex align-center justify-space-between px-4 px-md-6 pt-4 pt-md-5 pb-3">
      <div>
        <p class="text-overline mb-1">Carte interactive</p>
        <h3 class="text-h6 section-title mb-1">Stations visibles autour de vous</h3>
        <div class="d-flex flex-wrap ga-2">
          <v-chip
            color="primary"
            prepend-icon="mdi-fuel"
            variant="tonal"
          >
            {{ selectedFuel }}
          </v-chip>
          <v-chip
            color="secondary"
            prepend-icon="mdi-map-marker-multiple"
            variant="tonal"
          >
            {{ stations.length }} stations
          </v-chip>
          <v-chip
            color="accent"
            prepend-icon="mdi-radius"
            variant="tonal"
          >
            Rayon {{ radiusKm }} km
          </v-chip>
        </div>
      </div>

      <div class="d-flex ga-2">
        <v-btn
          color="secondary"
          icon="mdi-crosshairs-gps"
          variant="tonal"
          @click="recenterMap"
        />
        <v-btn
          color="secondary"
          :icon="isFullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen'"
          variant="tonal"
          @click="toggleFullscreen"
        />
      </div>
    </div>

    <div
      ref="mapShell"
      class="stations-map-shell"
      :class="{ 'stations-map-shell--fullscreen': isFullscreen }"
    >
      <div class="stations-map__aurora stations-map__aurora--top" />
      <div class="stations-map__aurora stations-map__aurora--bottom" />

      <div class="stations-map__legend">
        <div class="map-legend__item">
          <span class="map-legend__dot map-legend__dot--user" />
          <span>Votre position</span>
        </div>
        <div class="map-legend__item">
          <span class="map-legend__dot map-legend__dot--station" />
          <span>Station</span>
        </div>
        <div class="map-legend__item">
          <span class="map-legend__status map-legend__status--open" />
          <span>Ouverte</span>
        </div>
        <div class="map-legend__item">
          <span class="map-legend__status map-legend__status--closed" />
          <span>Fermee</span>
        </div>
        <div class="map-legend__item">
          <span class="map-legend__ring" />
          <span>Zone de recherche</span>
        </div>
        <div
          v-if="hasBestStation"
          class="map-legend__item"
        >
          <span class="map-legend__dot map-legend__dot--best" />
          <span>Meilleur prix recommande</span>
        </div>
      </div>

      <div class="stations-map__credit">
        Fond CARTO + OpenStreetMap
      </div>

      <div
        ref="mapElement"
        class="stations-map"
      />

      <transition name="map-sheet">
        <div
          v-if="selectedStation"
          class="map-selection-sheet"
          :class="{ 'map-selection-sheet--dark': themeName === 'fuelDark' }"
        >
          <div class="d-flex align-start justify-space-between ga-3 mb-2">
            <div>
              <p class="text-caption mb-1">{{ selectedStation.brand }}</p>
              <h4 class="map-selection-sheet__title mb-1">{{ selectedStation.name }}</h4>
              <p class="text-body-2 mb-0">{{ selectedStation.address }}, {{ selectedStation.city }}</p>
            </div>

            <v-btn
              :color="selectedStation.isFavorite ? 'accent' : 'secondary'"
              :icon="selectedStation.isFavorite ? 'mdi-star' : 'mdi-star-outline'"
              size="small"
              variant="text"
              @click="stationStore.toggleFavorite(selectedStation.id)"
            />
          </div>

          <div class="d-flex flex-wrap ga-2 mb-3">
            <v-chip
              color="primary"
              variant="tonal"
            >
              {{ selectedFuel }} - {{ formatPrice(selectedStation.selectedFuelPrice) }}
            </v-chip>
            <v-chip
              class="soft-chip"
              prepend-icon="mdi-map-marker-distance"
              variant="text"
            >
              {{ formatDistance(selectedStation.distanceKm) }}
            </v-chip>
            <v-chip
              class="soft-chip"
              prepend-icon="mdi-car-clock"
              variant="text"
            >
              ~ {{ formatDriveTime(selectedStation.estimatedDriveMinutes) }}
            </v-chip>
          </div>

          <div class="d-flex ga-2">
            <v-btn
              color="secondary"
              prepend-icon="mdi-eye-outline"
              variant="tonal"
              @click="openSelectedStation"
            >
              Voir details
            </v-btn>
            <v-btn
              color="primary"
              :href="getGoogleMapsDirectionsUrl(selectedStation.lat, selectedStation.lng)"
              prepend-icon="mdi-navigation-variant-outline"
              target="_blank"
            >
              Y aller
            </v-btn>
          </div>
        </div>
      </transition>
    </div>
  </v-card>
</template>

<style scoped>
.stations-map-shell {
  position: relative;
  padding: 0 1rem 1rem;
}

.stations-map-shell--fullscreen {
  position: fixed;
  inset: 0;
  z-index: 2000;
  padding: 1rem;
  background:
    radial-gradient(circle at top left, rgba(94, 234, 212, 0.18), transparent 24%),
    radial-gradient(circle at top right, rgba(255, 209, 102, 0.16), transparent 18%),
    rgba(10, 16, 24, 0.72);
  backdrop-filter: blur(18px);
}

.stations-map {
  min-height: 24rem;
  border-radius: 28px;
  overflow: hidden;
  border: 1px solid rgba(15, 23, 42, 0.08);
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.28),
    0 18px 40px rgba(15, 23, 42, 0.12);
}

.stations-map-shell--fullscreen .stations-map {
  min-height: calc(100vh - 2rem);
}

.stations-map__aurora {
  position: absolute;
  z-index: 2;
  width: 10rem;
  height: 10rem;
  border-radius: 999px;
  filter: blur(28px);
  pointer-events: none;
  opacity: 0.38;
}

.stations-map__aurora--top {
  top: -1.5rem;
  left: 1rem;
  background: rgba(94, 234, 212, 0.65);
}

.stations-map__aurora--bottom {
  right: 1.5rem;
  bottom: 1rem;
  background: rgba(255, 209, 102, 0.42);
}

.stations-map__legend {
  position: absolute;
  z-index: 3;
  top: 1rem;
  left: 2rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  max-width: calc(100% - 4rem);
  padding: 0.7rem 0.85rem;
  border: 1px solid rgba(255, 255, 255, 0.72);
  border-radius: 18px;
  background: rgba(255, 255, 255, 0.84);
  backdrop-filter: blur(12px);
  box-shadow: 0 14px 34px rgba(15, 23, 42, 0.12);
}

.stations-map__credit {
  position: absolute;
  z-index: 3;
  right: 2rem;
  bottom: 2rem;
  padding: 0.45rem 0.7rem;
  border-radius: 999px;
  background: rgba(15, 23, 42, 0.7);
  color: rgba(255, 255, 255, 0.86);
  font-size: 0.74rem;
  letter-spacing: 0.01em;
  backdrop-filter: blur(10px);
}

.map-legend__item {
  display: inline-flex;
  align-items: center;
  gap: 0.45rem;
  font-size: 0.8rem;
  font-weight: 700;
  color: rgba(15, 23, 42, 0.82);
}

.map-legend__dot {
  width: 0.8rem;
  height: 0.8rem;
  border-radius: 999px;
  box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.65);
}

.map-legend__status {
  width: 0.7rem;
  height: 0.7rem;
  border-radius: 999px;
}

.map-legend__status--open {
  background: #0f766e;
}

.map-legend__status--closed {
  background: #b91c1c;
}

.map-legend__ring {
  width: 0.9rem;
  height: 0.9rem;
  border: 2px dashed rgba(15, 118, 110, 0.9);
  border-radius: 999px;
}

.map-legend__dot--user {
  background: #0f172a;
}

.map-legend__dot--station {
  background: #0f766e;
}

.map-legend__dot--best {
  background: #ffb703;
}

.map-selection-sheet {
  position: absolute;
  z-index: 4;
  right: 1.25rem;
  bottom: 1.25rem;
  left: 1.25rem;
  padding: 1rem;
  border-radius: 24px;
  background: rgba(255, 255, 255, 0.92);
  border: 1px solid rgba(255, 255, 255, 0.72);
  box-shadow: 0 22px 50px rgba(15, 23, 42, 0.22);
  backdrop-filter: blur(18px);
}

.map-selection-sheet--dark {
  border-color: rgba(125, 211, 252, 0.12);
  background: linear-gradient(180deg, rgba(7, 22, 28, 0.92), rgba(13, 31, 39, 0.9));
  box-shadow: 0 22px 50px rgba(0, 0, 0, 0.35);
  color: rgba(226, 247, 241, 0.82);
}

.map-selection-sheet--dark .map-selection-sheet__title {
  color: #f8fafc;
}

.map-selection-sheet--dark .text-caption,
.map-selection-sheet--dark .text-body-2 {
  color: rgba(226, 247, 241, 0.78) !important;
}

.map-selection-sheet--dark .soft-chip {
  color: rgba(226, 247, 241, 0.88);
}

.map-selection-sheet__title {
  font-family: var(--ff-display);
  font-size: 1.05rem;
  line-height: 1.15;
}

.map-sheet-enter-active,
.map-sheet-leave-active {
  transition:
    opacity 0.2s ease,
    transform 0.2s ease;
}

.map-sheet-enter-from,
.map-sheet-leave-to {
  opacity: 0;
  transform: translateY(10px);
}

:global(.v-theme--fuelDark) .stations-map {
  border-color: rgba(125, 211, 252, 0.1);
}

:global(.v-theme--fuelDark) .stations-map__legend {
  border-color: rgba(125, 211, 252, 0.12);
  background: rgba(7, 22, 28, 0.74);
}

:global(.v-theme--fuelDark) .map-legend__item {
  color: rgba(226, 247, 241, 0.86);
}

:global(.v-theme--fuelDark) .map-legend__ring {
  border-color: rgba(94, 234, 212, 0.9);
}

:global(.v-theme--fuelDark) .stations-map__credit {
  background: rgba(7, 22, 28, 0.76);
  color: rgba(226, 247, 241, 0.8);
}

@media (min-width: 960px) {
  .stations-map-shell {
    padding: 0 1.5rem 1.5rem;
  }

  .stations-map {
    min-height: 30rem;
  }

  .map-selection-sheet {
    width: min(27rem, calc(100% - 3rem));
    left: auto;
  }
}

@media (max-width: 600px) {
  .stations-map__legend {
    top: 0.8rem;
    left: 1.2rem;
    right: 1.2rem;
    max-width: none;
  }

  .stations-map__credit {
    left: 1.2rem;
    right: auto;
    bottom: 7.8rem;
  }

  .map-selection-sheet {
    bottom: 1rem;
  }
}
</style>

// src/components/map/StationsMap.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { Expand, LocateFixed, Navigation, Star } from "lucide-react";
import L from "leaflet";
import "leaflet.markercluster";
import { Circle, MapContainer, Marker, TileLayer, useMap } from "react-leaflet";
import { useNavigate } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { formatDistance, formatDriveTime, formatPrice } from "@/utils/format";
import { getGoogleMapsDirectionsUrl } from "@/utils/navigation";
import { useFuelStationsStore } from "@/store/useFuelStationsStore";
import { cn } from "@/lib/utils";
import type { Coordinates, FuelType, StationWithMetrics } from "@/types/station";

const userIcon = L.divIcon({
  className: "map-user-marker",
  html: '<div class="h-6 w-6 rounded-full border-4 border-teal-300 bg-slate-900 shadow-lg"></div>',
  iconSize: [24, 24],
  iconAnchor: [12, 12],
});

const createStationIcon = (best: boolean, open: boolean, showPrice: boolean, price?: string) =>
  L.divIcon({
    className: "",
    html: `
      <div class="relative">
        <div class="${best ? "animate-pulsepin bg-amber-400" : "bg-teal-600"} h-6 w-6 rounded-full border-4 border-white shadow-lg"></div>
        <div class="absolute -right-0.5 -top-0.5 h-3 w-3 rounded-full border border-white ${open ? "bg-emerald-500" : "bg-red-500"}"></div>
        ${showPrice && price ? `<div class="absolute -top-9 left-1/2 -translate-x-1/2 rounded-full bg-slate-900 px-2 py-1 text-[10px] font-bold text-white">${price}</div>` : ""}
      </div>
    `,
    iconSize: [24, 24],
    iconAnchor: [12, 12],
  });

const ClusteredStationsLayer = ({
  stations,
  selectedFuel,
  bestStationId,
  onSelectStation,
}: {
  stations: StationWithMetrics[];
  selectedFuel: FuelType;
  bestStationId: string | null;
  onSelectStation: (station: StationWithMetrics) => void;
}) => {
  const map = useMap();
  const clusterLayerRef = useRef<L.MarkerClusterGroup | null>(null);

  useEffect(() => {
    const clusterLayer =
      clusterLayerRef.current ??
      L.markerClusterGroup({
        showCoverageOnHover: false,
        maxClusterRadius: 56,
        iconCreateFunction: (cluster) =>
          L.divIcon({
            className: "map-cluster",
            html: `<span>${cluster.getChildCount()}</span>`,
            iconSize: [44, 44],
          }),
      });

    clusterLayer.clearLayers();

    stations.forEach((station, index) => {
      const marker = L.marker([station.lat, station.lng], {
        icon: createStationIcon(
          station.id === bestStationId,
          station.isOpen,
          station.id === bestStationId || index < 2,
          station.selectedFuelPrice != null ? formatPrice(station.selectedFuelPrice) : undefined,
        ),
      });

      marker.bindPopup(`
        <div class="map-popup">
          <h4 class="map-popup__title">${station.name}</h4>
          <p class="map-popup__meta">${station.address}, ${station.city}</p>
          <p class="map-popup__meta">${selectedFuel} - ${formatPrice(station.selectedFuelPrice)}</p>
          <p class="map-popup__meta">${formatDistance(station.distanceKm)} - ~ ${formatDriveTime(station.estimatedDriveMinutes)}</p>
          <div class="map-popup__actions">
            <a class="map-popup__button" href="/station/${station.id}">Voir details</a>
            <a class="map-popup__button map-popup__button--ghost" href="${getGoogleMapsDirectionsUrl(station.lat, station.lng)}" target="_blank" rel="noopener noreferrer">Y aller</a>
          </div>
        </div>
      `);

      marker.on("click", () => onSelectStation(station));
      clusterLayer.addLayer(marker);
    });

    if (!clusterLayerRef.current) {
      clusterLayerRef.current = clusterLayer;
      map.addLayer(clusterLayer);
    }

    return () => {
      map.removeLayer(clusterLayer);
      clusterLayerRef.current = null;
    };
  }, [bestStationId, map, onSelectStation, selectedFuel, stations]);

  return null;
};

const FitBounds = ({ bounds }: { bounds: L.LatLngBoundsExpression | null }) => {
  const map = useMap();

  useEffect(() => {
    if (bounds) {
      map.fitBounds(bounds, { padding: [40, 40], maxZoom: 14 });
    }
  }, [bounds, map]);

  return null;
};

interface StationsMapProps {
  userPosition: Coordinates | null;
  stations: StationWithMetrics[];
  selectedFuel: FuelType;
  radiusKm: number;
  bestStationId?: string | null;
}

export const StationsMap = ({
  userPosition,
  stations,
  selectedFuel,
  radiusKm,
  bestStationId = null,
}: StationsMapProps) => {
  const navigate = useNavigate();
  const [selectedStation, setSelectedStation] = useState<StationWithMetrics | null>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const themeName = useFuelStationsStore((state) => state.themeName);
  const toggleFavorite = useFuelStationsStore((state) => state.toggleFavorite);
  const mapShellRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<L.Map | null>(null);

  const tileLayerConfig = useMemo(
    () =>
      themeName === "fuelDark"
        ? {
            url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
            attribution: "&copy; OpenStreetMap contributors &copy; CARTO",
          }
        : {
            url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
            attribution: "&copy; OpenStreetMap contributors &copy; CARTO",
          },
    [themeName],
  );

  const bounds = useMemo(() => {
    if (!userPosition && stations.length === 0) {
      return null;
    }

    const latLngs: L.LatLngTuple[] = stations.map((station) => [station.lat, station.lng]);
    if (userPosition) {
      latLngs.push([userPosition.lat, userPosition.lng]);
      const searchBounds = L.latLng([userPosition.lat, userPosition.lng]).toBounds(radiusKm * 1000);
      latLngs.push([searchBounds.getNorthEast().lat, searchBounds.getNorthEast().lng]);
      latLngs.push([searchBounds.getSouthWest().lat, searchBounds.getSouthWest().lng]);
    }
    return L.latLngBounds(latLngs);
  }, [radiusKm, stations, userPosition]);

  useEffect(() => {
    if (!selectedStation && bestStationId) {
      setSelectedStation(stations.find((station) => station.id === bestStationId) ?? null);
    }
  }, [bestStationId, selectedStation, stations]);

  useEffect(() => {
    const syncFullscreenState = () => setIsFullscreen(document.fullscreenElement === mapShellRef.current);
    document.addEventListener("fullscreenchange", syncFullscreenState);
    return () => document.removeEventListener("fullscreenchange", syncFullscreenState);
  }, []);

  const handleFullscreen = async () => {
    if (!mapShellRef.current) {
      return;
    }

    if (document.fullscreenElement === mapShellRef.current) {
      await document.exitFullscreen();
    } else {
      await mapShellRef.current.requestFullscreen();
    }

    setTimeout(() => {
      mapRef.current?.invalidateSize();
    }, 120);
  };

  const recenterMap = () => {
    if (bounds) {
      mapRef.current?.fitBounds(bounds, { padding: [40, 40], maxZoom: 14 });
    }
  };

  return (
    <Card className="overflow-hidden">
      <CardContent className="space-y-4 p-0">
        <div className="flex flex-col gap-4 px-5 pt-5 md:flex-row md:items-start md:justify-between">
          <div className="space-y-3">
            <div>
              <p className="text-xs font-extrabold uppercase tracking-[0.24em] text-primary">Carte interactive</p>
              <h3 className="font-display text-xl tracking-tight">Stations visibles autour de vous</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              <Badge>{selectedFuel}</Badge>
              <Badge variant="secondary">{stations.length} stations</Badge>
              <Badge variant="accent">Rayon {radiusKm} km</Badge>
            </div>
          </div>

          <div className="flex gap-2">
            <Button onClick={recenterMap} size="icon" variant="tonal">
              <LocateFixed className="h-4 w-4" />
            </Button>
            <Button onClick={handleFullscreen} size="icon" variant="tonal">
              <Expand className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div
          className={cn(
            "relative px-4 pb-4 md:px-5 md:pb-5",
            isFullscreen && "bg-slate-950/90 px-4 py-4 backdrop-blur-xl",
          )}
          ref={mapShellRef}
        >
          <div className="pointer-events-none absolute left-8 top-4 z-[500] flex max-w-[calc(100%-4rem)] flex-wrap gap-2 rounded-full border border-white/50 bg-white/80 px-3 py-2 text-xs font-semibold shadow-lg backdrop-blur dark:border-white/10 dark:bg-slate-950/70">
            <span>Votre position</span>
            <span>•</span>
            <span>Zone de recherche</span>
            {bestStationId ? (
              <>
                <span>•</span>
                <span>Meilleur prix recommande</span>
              </>
            ) : null}
          </div>

          <div className={cn("overflow-hidden rounded-[28px] border", isFullscreen ? "h-[calc(100vh-2rem)]" : "h-[26rem] md:h-[32rem]")}>
            <MapContainer
              center={userPosition ? [userPosition.lat, userPosition.lng] : [48.8566, 2.3522]}
              className="h-full w-full"
              ref={(instance) => {
                mapRef.current = instance;
              }}
              zoom={12}
            >
              <TileLayer attribution={tileLayerConfig.attribution} url={tileLayerConfig.url} />
              {bounds ? <FitBounds bounds={bounds} /> : null}
              {userPosition ? (
                <>
                  <Circle center={[userPosition.lat, userPosition.lng]} pathOptions={{ color: "#0f766e", dashArray: "8 8" }} radius={radiusKm * 1000} />
                  <Circle center={[userPosition.lat, userPosition.lng]} pathOptions={{ color: "#0f766e", fillColor: "#5eead4", fillOpacity: 0.2 }} radius={260} />
                  <Marker icon={userIcon} position={[userPosition.lat, userPosition.lng]} />
                </>
              ) : null}
              <ClusteredStationsLayer
                bestStationId={bestStationId}
                onSelectStation={setSelectedStation}
                selectedFuel={selectedFuel}
                stations={stations}
              />
            </MapContainer>
          </div>

          {selectedStation ? (
            <div className="absolute inset-x-4 bottom-4 z-[500] rounded-[24px] border border-white/40 bg-white/90 p-4 shadow-2xl backdrop-blur md:left-auto md:w-[26rem] dark:border-white/10 dark:bg-slate-950/85">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">{selectedStation.brand}</p>
                  <h4 className="font-display text-lg tracking-tight">{selectedStation.name}</h4>
                  <p className="text-sm text-muted-foreground">
                    {selectedStation.address}, {selectedStation.city}
                  </p>
                </div>
                <button onClick={() => toggleFavorite(selectedStation.id)} type="button">
                  <Star className={`h-5 w-5 ${selectedStation.isFavorite ? "fill-current text-amber-500" : "text-muted-foreground"}`} />
                </button>
              </div>

              <div className="mt-3 flex flex-wrap gap-2">
                <Badge>{selectedFuel} • {formatPrice(selectedStation.selectedFuelPrice)}</Badge>
                <Badge variant="secondary">{formatDistance(selectedStation.distanceKm)}</Badge>
                <Badge variant="secondary">~ {formatDriveTime(selectedStation.estimatedDriveMinutes)}</Badge>
              </div>

              <div className="mt-4 flex gap-2">
                <Button onClick={() => navigate(`/station/${selectedStation.id}`)} variant="tonal">
                  Voir details
                </Button>
                <Button asChild>
                  <a href={getGoogleMapsDirectionsUrl(selectedStation.lat, selectedStation.lng)} rel="noreferrer" target="_blank">
                    <Navigation className="h-4 w-4" />
                    Y aller
                  </a>
                </Button>
              </div>
            </div>
          ) : null}
        </div>
      </CardContent>
    </Card>
  );
};
